In [18]:
#list와 array의 차이점

In [4]:
import numpy as np
x = np.array([1, 2, 3])
print(x)

[1 2 3]


In [8]:
x = np.array([1,2,3,'a','b'])
y = [1,2,3,'a','b']
print(x)
print(y)

['1' '2' '3' 'a' 'b']
[1, 2, 3, 'a', 'b']


In [16]:
list1 = [1,2,3]
list2 = [4,5,6]
print(list1 + list2)
print(list1 * 2)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3]


In [19]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a*b)
print(a * 2)

[5 7 9]
[ 4 10 18]
[2 4 6]


In [27]:
print(a.ndim) #몇 차원인지 보여줌
print(a.shape) # 몇 행 몇 열인지 보여줌

2
(2, 2)


In [29]:
a = np.array([[1,2], [2,3]])
a.ndim
a.shape

(2, 2)

In [31]:
#행렬 연산 메소드 : (dot() & matmul())

In [37]:
# dot() : 스칼라의 곱
# 1차원 행렬의 내적연산
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.dot(a,b))
# matmul() : 2차원 행렬의 곱
# 2차원 행렬 내적연산
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[6,3],[5,2],[4,1]])
print(np.matmul(c,d))

32
[[28 10]
 [73 28]]


In [38]:
#영행렬 생성

In [45]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [46]:
#단위행렬 생성

In [48]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [50]:
#행렬의 평탄화 작업 : .flatten()

In [53]:
a = np.array([[2,3], [1,4]])
print(a)
print(a.flatten())

[[2 3]
 [1 4]]
[2 3 1 4]


In [54]:
#행렬의 차원을 변경 : .reshape()

In [57]:
a = np.array([[1,2,3], [1,4,5]])
print(a.reshape(3,2)) #2x3행렬 -> 3x2행렬
# 주의할 점 : 원소의 갯수가 같아야함

[[1 2]
 [3 1]
 [4 5]]


In [58]:
#특정배열의 만듦 : .arange()

In [63]:
a = np.arange(5,10,2)#5부터 10까지 2씩 추가하며 행렬생성
b = range(5)
print(a)
print(b)

[5 7 9]
range(0, 5)


In [64]:
# 난수생성

In [65]:
#.random.randint()
#.random.rand(m,n)

In [75]:
np.random.randint(5,size = (2,3))
# 0~5사이 값이 랜덤으로 2x3행렬생성

array([[0, 2, 3],
       [2, 2, 4]])

In [77]:
np.random.rand(3,4)
#0~1사이 값이 랜덤으로 행렬생성

array([[0.93490029, 0.41344019, 0.10931396, 0.97744192],
       [0.16344703, 0.93435948, 0.64755327, 0.00131962],
       [0.46255342, 0.05573828, 0.40698993, 0.76938075]])

In [78]:
#조건 인덱싱

In [80]:
a = np.array([[1,2],[3,4],[5,6]])
a > 4

array([[False, False],
       [False, False],
       [ True,  True]])

In [83]:
a = np.array([[1,2],[3,4],[5,6]])
a[a > 4] # 내부조건을 만족하는 행렬 인덱싱

array([5, 6])

In [109]:
#실습1(1~5번)

In [150]:
a = np.zeros(10)
print(np.zeros(10))
a[4] = 1
print(a)
c = np.arange(10,31,1)
print(c)
d = np.random.randint(100,size = (2,2))
print(d)
e = np.random.rand(2,4)
print(e)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
[[34 46]
 [47 95]]
[[0.31888157 0.58600159 0.06742315 0.7906237 ]
 [0.29138711 0.52253935 0.66144458 0.84017028]]


In [110]:
#실습2(6~8번)

In [161]:
a = np.arange(35,75,1)
print(a)
b = a.reshape(10,4)
print(b)
c = np.flip(b,axis = 0)
print(c)
print(b[1:-1 , 2:])


[35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58
 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74]
[[35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]
 [47 48 49 50]
 [51 52 53 54]
 [55 56 57 58]
 [59 60 61 62]
 [63 64 65 66]
 [67 68 69 70]
 [71 72 73 74]]
[[71 72 73 74]
 [67 68 69 70]
 [63 64 65 66]
 [59 60 61 62]
 [55 56 57 58]
 [51 52 53 54]
 [47 48 49 50]
 [43 44 45 46]
 [39 40 41 42]
 [35 36 37 38]]
[[41 42]
 [45 46]
 [49 50]
 [53 54]
 [57 58]
 [61 62]
 [65 66]
 [69 70]]


In [135]:
#실습3(9~11번)

In [166]:
c = b[:,-1]
print(c)
d = b[:, -1:]
print(d)
e = np.flip(d, axis = 0)
print(e)
f = np.random.randint(1,51,size = (5,6))
print(f)
g =f[f % 2 == 0]
print(g)


[38 42 46 50 54 58 62 66 70 74]
[[38]
 [42]
 [46]
 [50]
 [54]
 [58]
 [62]
 [66]
 [70]
 [74]]
[[74]
 [70]
 [66]
 [62]
 [58]
 [54]
 [50]
 [46]
 [42]
 [38]]
[[25 10 42 18 10 43]
 [15 30 46  9 38 18]
 [50 31 22 36 14 13]
 [36  6 24 40 17  9]
 [ 1 42 21  2  3  3]]
[10 42 18 10 30 46 38 18 50 22 36 14 36  6 24 40 42  2]
